# PyTorch基本操作

In [1]:
import torch

创建一个2x4的二维张量

In [3]:
x = torch.Tensor(2, 4)

In [4]:
print(x.type())
print(x.dtype)

torch.FloatTensor
torch.float32


创建全为0的张量

In [11]:
torch.zeros(3, 3, 2)

tensor([[[0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.]]])

创建对角线全为1的张量

In [ ]:
torch.eye(2,4)

tensor([[1., 0., 0., 0.],
        [0., 1., 0., 0.]])

随机创建Tensor在区间(0, 1]

In [ ]:
torch.rand(3, 4, 2)

tensor([[[0.6119, 0.1872],
         [0.2839, 0.0886],
         [0.7623, 0.9628],
         [0.5403, 0.6773]],

        [[0.0132, 0.9709],
         [0.3423, 0.7638],
         [0.8280, 0.9459],
         [0.6073, 0.7468]],

        [[0.2180, 0.3269],
         [0.6787, 0.2352],
         [0.3193, 0.2941],
         [0.3633, 0.0231]]])

创建等间隔的1维张量

In [ ]:
torch.linspace(0, 10, steps=5)

tensor([ 0.0000,  2.5000,  5.0000,  7.5000, 10.0000])

点积运算（向量与向量）

In [15]:
a = torch.Tensor([1, 2, 3])
b = torch.Tensor([4, 5, 6])
torch.dot(a, b)

tensor(32.)

矩阵与向量的乘法

In [17]:
a = torch.Tensor([1, 2, 3])
b = torch.Tensor([[1,2,3], [2, 3, 4], [4, 4, 1]])
torch.mv(b, a)

tensor([14., 20., 15.])

两个矩阵的乘法

In [18]:
a = torch.Tensor([[1,2,3], [2,3,4], [3,4,5]])
b = torch.Tensor([[2,3,4], [3,4,5], [4,5,6]])
torch.mm(a, b)

tensor([[20., 26., 32.],
        [29., 38., 47.],
        [38., 50., 62.]])

In [19]:
a = torch.Tensor([1, 2, 3])
b = torch.Tensor([2, 3, 4])
torch.ger(a, b)

tensor([[ 2.,  3.,  4.],
        [ 4.,  6.,  8.],
        [ 6.,  9., 12.]])

转置

In [24]:
a = torch.rand(2, 3)
a

tensor([[0.5295, 0.9828, 0.5406],
        [0.2363, 0.8571, 0.2585]])

In [25]:
torch.t(a)

tensor([[0.5295, 0.2363],
        [0.9828, 0.8571],
        [0.5406, 0.2585]])

In [26]:
a = torch.rand(3, 4)
a

tensor([[0.0136, 0.7229, 0.0135, 0.2074],
        [0.1878, 0.9282, 0.8585, 0.5948],
        [0.6392, 0.4713, 0.2584, 0.4072]])

In [27]:
torch.t(a)

tensor([[0.0136, 0.1878, 0.6392],
        [0.7229, 0.9282, 0.4713],
        [0.0135, 0.8585, 0.2584],
        [0.2074, 0.5948, 0.4072]])