# Autograd自动微分

In [33]:
import torch

In [34]:
x = torch.ones(2) # 叶子节点

查看require_grad属性

In [35]:
x.requires_grad

False

In [36]:
x.requires_grad = True
x

tensor([1., 1.], requires_grad=True)

打印叶子节点的grad和grad_fn的值

In [37]:
x.grad
x.grad_fn

In [38]:
z = x * 4

In [39]:
z

tensor([4., 4.], grad_fn=<MulBackward0>)

In [40]:
y = z.norm() # y是一个标量, 向量z的长度

In [41]:
y

tensor(5.6569, grad_fn=<LinalgVectorNormBackward0>)

反向传播

In [42]:
y.backward()

In [43]:
x.grad

tensor([2.8284, 2.8284])

In [44]:
z.grad

C:\Users\宋\AppData\Local\Temp\ipykernel_16228\4110045842.py:1: UserWarning: The .grad attribute of a Tensor that is not a leaf Tensor is being accessed. Its .grad attribute won't be populated during autograd.backward(). If you indeed want the .grad field to be populated for a non-leaf Tensor, use .retain_grad() on the non-leaf Tensor. If you access the non-leaf Tensor by mistake, make sure you access the leaf Tensor instead. See github.com/pytorch/pytorch/pull/30531 for more informations. (Triggered internally at C:\actions-runner\_work\pytorch\pytorch\pytorch\build\aten\src\ATen/core/TensorBody.h:494.)
  z.grad


In [45]:
y.grad

C:\Users\宋\AppData\Local\Temp\ipykernel_16228\486760323.py:1: UserWarning: The .grad attribute of a Tensor that is not a leaf Tensor is being accessed. Its .grad attribute won't be populated during autograd.backward(). If you indeed want the .grad field to be populated for a non-leaf Tensor, use .retain_grad() on the non-leaf Tensor. If you access the non-leaf Tensor by mistake, make sure you access the leaf Tensor instead. See github.com/pytorch/pytorch/pull/30531 for more informations. (Triggered internally at C:\actions-runner\_work\pytorch\pytorch\pytorch\build\aten\src\ATen/core/TensorBody.h:494.)
  y.grad


非标量输出

In [46]:
a = torch.ones(2,1)
a

tensor([[1.],
        [1.]])

In [47]:
b = torch.Tensor([[2, 3], [1, 2]])
b.requires_grad = True

In [48]:
y = torch.mm(b, a)
y

tensor([[5.],
        [3.]], grad_fn=<MmBackward0>)

In [49]:
y.backward(torch.ones(2, 1)) 
b.grad

tensor([[1., 1.],
        [1., 1.]])

In [51]:
print(a.grad)

None
