In [1]:
import torch
from torch.nn import functional as F
from torch import nn, optim
import matplotlib.pyplot as plt

In [29]:
x = torch.Tensor([[200.0, 17.0]])

In [30]:
layer1 = nn.Linear(2, 3)

In [31]:
a1 = torch.sigmoid(layer1(x))

In [36]:
a1

tensor([[1., 0., 1.]], grad_fn=<SigmoidBackward0>)

In [37]:
layer2 = nn.Linear(3, 1)

In [38]:
a2 = torch.sigmoid(layer2(a1))

In [39]:
a2

tensor([[0.4187]], grad_fn=<SigmoidBackward0>)

In [41]:
a2.data.numpy()

array([[0.41872075]], dtype=float32)